version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017' # expose le port MongoDB
    volumes:
      - ./mongo_data:/data/db # persiste les données dans un répertoire local
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - '8081:8081' # expose l'interface web de mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
