export const StatusOffer = {
  SENT: 'SENT',
  FOLLOWED_UP: 'FOLLOWED_UP',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  AWAITING_RESPONSE: 'AWAITING_RESPONSE',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
};
